
-- DROP tables
DROP TABLE IF EXISTS "public".ERS_USERS CASCADE;
DROP TABLE IF EXISTS "public".ERS_REIMBURSMENT CASCADE;

--Create Enum Types
CREATE TYPE "public".ROLE AS ENUM ('Employee','Manager');
CREATE TYPE "public".REMB_TYPE AS ENUM ('Lodging','Travel','Food','Other');
CREATE TYPE "public".STATUS AS ENUM ('Pending','Approved','Denied');

-- Create USERS Table
CREATE TABLE "public".ERS_USERS
(
    USERID      SERIAL PRIMARY KEY,
    USERNAME 	VARCHAR(250)  UNIQUE NOT NULL,
    PASSWORD    VARCHAR(250)  NOT NULL,
    ROLE        VARCHAR(250)  NOT NULL
);

-- Create REIMBURSMENT Table
CREATE TABLE "public".ERS_REIMBURSMENT
(
    ID          	SERIAL PRIMARY KEY NOT NULL,
    AUTHOR			INT REFERENCES "public".ERS_USERS(USERID),
    RESOLVER		INT REFERENCES "public".ERS_USERS(USERID),
    DESCRIPTION 	TEXT,
    TYPE      		REMB_TYPE,
    STATUS      	STATUS,
    AMOUNT			NUMERIC
);

-- Insert Test Data in to REIMBURSMENT table
INSERT INTO "public".ERS_USERS(USERNAME, PASSWORD, ROLE)	VALUES ('Michel', 'Michel123', 'Employee');
INSERT INTO "public".ERS_USERS(USERNAME, PASSWORD, ROLE)	VALUES ('Kim', 'Welcome123', 'Employee');
INSERT INTO "public".ERS_USERS(USERNAME, PASSWORD, ROLE)	VALUES ('MadOP', 'Mad06', 'Manager');
INSERT INTO "public".ERS_USERS(USERNAME, PASSWORD, ROLE)	VALUES ('KiaK', 'K1@45', 'Employee');

-- Insert Test Data in to USERS table
INSERT INTO "public".ERS_REIMBURSMENT(AUTHOR, DESCRIPTION, TYPE, STATUS, AMOUNT) VALUES (1, 'Test Description One from 1', 'Lodging', 'Pending', 20000);
INSERT INTO "public".ERS_REIMBURSMENT(AUTHOR, DESCRIPTION, TYPE, STATUS, AMOUNT) VALUES (1, 'Test Description Two from 1 ', 'Travel', 'Pending', 56400);
INSERT INTO "public".ERS_REIMBURSMENT(AUTHOR, DESCRIPTION, TYPE, STATUS, AMOUNT) VALUES (1, 'Test Description Three from 1', 'Food', 'Pending', 32622523);
INSERT INTO "public".ERS_REIMBURSMENT(AUTHOR, DESCRIPTION, TYPE, STATUS, AMOUNT) VALUES (2, 'Test Description Four from 2', 'Food', 'Pending', 4432543);
INSERT INTO "public".ERS_REIMBURSMENT(AUTHOR, DESCRIPTION, TYPE, STATUS, AMOUNT) VALUES (3, 'Test Description Five from 3', 'Travel', 'Pending', 634253454);